### ISSUE TITLE
EBWebView directory

### ISSUE THREAD

**Issue by pryrt** [Ekopalypse/NppLspClient#24]
When I'm using NppLspClient (0.0.30-alpha) with perl (pernavigator.exe as the LSP server), it will create an EBWebView directory.

Sometimes, it creates it in `plugins\config\NppLspClient\EBWebView` ... but sometimes, it's created it as `蝰翽\EBWebView` [U+8770 U+F869 U+7FFD] off the notepad++.exe's directory.  (When I was previously using 0.0.27-alpha, it was creating it as `notepad++.exe.WebView2` when in the executable's directory)

When it's in the portable, the `蝰翽\EBWebView` directory isn't a big problem, but when it's trying to create it in the `C:\Program Files\Notepad++\` with UAC issues, that can be problematic.

I was hoping that once it created it, it would stop trying in the other locations.  But after running and exiting Notepad++ a few times, with different files as the focus (sometimes with the perl focused, sometimes with text focused), it would sometimes create the `蝰翽\EBWebView` again, even though `plugins\config\NppLspClient\EBWebView` still exists.  (Sorry, I haven't been able to figure out the exact sequence of events that puts it into the executable directory yet.)

So first, is that directory necessary?  Because the ~10M going into `plugins\config\NppLspClient\EBWebView` seems excessive. Or is there some way to force it to be in %TEMP% all the time, rather than trying any of the other locations?

And second, if it is needed, is there a way that it could more consistently make it into the config hierarchy

**Comment by Ekopalypse** [comment]
I don't see this behavior on my site and it should actually always be created in the plugin config directory.
In the NPPN_READY notification, the hover dialog is created and the webview component gets the plugin config directory via the NPPM_GETPLUGINSCONFIGDIR message. 
This must therefore mean that for whatever reason nothing is returned here. Which is actually strange. And do I understand correctly that the EBWebView is created in the application directory during runtime? That's even stranger ... !!??

As for the directory itself and its size, it is the cache directory of the [MS Webview](https://learn.microsoft.com/en-us/microsoft-edge/webview2/) component and I must admit that I have not (yet) taken the trouble to investigate its behavior more closely.

**Comment by Ekopalypse** [comment]
@pryrt 
Bug confirmed, I can reproduce it when I start a second instance of Npp. Thank you for reporting the issue.

**Comment by Ekopalypse** [comment]
@pryrt - should be fixed in release v_0.0.31.

**Comment by pryrt** [comment]
With my experiments so far, 0.0.31 seems to fix it (it also cleans up that folder when Notepad++ exits, which is nice; thanks).  I'll let you know if it comes back.
