### ISSUE TITLE
Error: "Cannot open file"

### ISSUE THREAD

**Issue by pryrt** [Ekopalypse/NppLspClient#3]
Since [I mentioned your plugin](https://community.notepad-plus-plus.org/topic/22934/importing-pythonscript-library-to-ide/2) today, and had a few spare minutes, I finally got it working with my python2.7 installation (I couldn't install python-lsp-server as you had suggested [in October](https://community.notepad-plus-plus.org/post/70944), but I found that I could install python-language-server with pip2 and got pyls that way... and once I saw that the config file language had changed from JSON to TOML, I was able to get either the IO or the TCP pointed at the pyls.exe and working.  🎉

As I was trying some features, I was surprised to see when looking in my `startup.py` where I import some of my scripts to automatically run, on the ones that were correctly defined with a docstring at the beginning, hovering correctly worked... so it was correctly finding the right module in the search path, which highly impressed me!

But then I tried to **NppLspClient > Goto Definition** on the same one, and it popped up the error:

![image](https://user-images.githubusercontent.com/17455758/165991249-74ce8b2f-0615-4460-a802-1330573b4348.png)

I tried on a standard library (like `import os`) and it correctly went to the definition (which told me the feature itself is functional).  But apparently the `++` being translated to `%2B%2B` messed up whatever underlying open function is being used.

Looking at the log, the only mentions of `%2B` were here:
```
2022-04-29 10:22:51,976 UTC - DEBUG - pyls.config.config -   finish pyls_definitions --> [[{'range': {'start': {'line': 0, 'character': 0}, 'end': {'line': 0, 'character': 20}}, 'uri': 'file:///c:/Users/peter.jones/AppData/Roaming/Notepad%2B%2B/plugins/Config/PythonScript/scripts/nppOnSaveSyntaxCheck.py'}]] [hook]

2022-04-29 10:22:51,976 UTC - DEBUG - pyls_jsonrpc.endpoint - Got result from synchronous request handler: [{'range': {'start': {'line': 0, 'character': 0}, 'end': {'line': 0, 'character': 20}}, 'uri': 'file:///c:/Users/peter.jones/AppData/Roaming/Notepad%2B%2B/plugins/Config/PythonScript/scripts/nppOnSaveSyntaxCheck.py'}]
```

**Comment by Ekopalypse** [comment]
Thank you, yes, I can confirm and reproduce this problem.
A path must be encoded as [URI](https://microsoft.github.io/language-server-protocol/specification#uri), which must be en- and decoded accordingly.
The problem will be fixed with the next version.

**Comment by Ekopalypse** [comment]
Fixed with latest release
